### PR TITLE
fix tests, improve libxlsxwriter loading process

### PR DESCRIPTION
**Pull request by sly7-7**
Adresses https://github.com/Paxa/fast_excel/pull/91#discussion_r1063567480

cc/ @Paxa @BrianHawley

### CODE REVIEW

**Comment by sly7-7** [comment]
@cmer When this is merged, you could close #90.

@Mange Maybe you could be interrested as well as I saw you were reporting the issue.

**Comment by BrianHawley** [comment]
@sly7-7 it looks good to me. Good to see tests pass.

**Comment by Mange** [comment]
I might check this out at work tomorrow and check!

**Comment by duffyjp** [comment]
@Paxa When this one is set, can we get a new gem release?  Thanks!

**Comment by Paxa** [comment]
Thank you, I will make some manual testing and will try to make new version today

**Comment by Mange** [comment]
Swithed to `master` branch and ran `bundle update fast_excel; bundle pristine fast_excel`.

Everything seem to be working. :-)

**Comment by Paxa** [comment]
Published version 0.4.1, thank you all

**Pull request merged**
